#! /bin/bash


export ACCESS_TOKEN_FILE=/tmp/av-access-token
export API_URL_FILE=/tmp/av-api-url
export VI_FILE=/tmp/av-vi



########################################################################################################################
# Initializes client id and client secret according to the given host name
#     --> $2: host --> the host name, such as qa-trunk.airvantage.net
########################################################################################################################

_api_client () {
    HOST=$2

    if test "$HOST" = "qa-trunk.airvantage.net"
    then
        clientId=890a211eefbc4f1391980984135ebb86
        clientSecret=e36691e8a022440fa44b6eecd007a06d
    elif test "$HOST" = "qa-branch.airvantage.net"
    then
        clientId=4e41c4ad716446a380a917700cbaa845
        clientSecret=671b5962e30041c69c0a3cc532e343a2
    elif test "$HOST" = "dev-airlink.airvantage.net"
    then
        clientId=a14979078246475fafc203fe56f6f3b4
        clientSecret=5ede19e06b8f40858e20baed02627cd3
    elif test "$HOST" = "edge.airvantage.net"
    then
        clientId=086ad0284d18465386420271b089de89
        clientSecret=0ed2ae955ba546c6806d79db63b6e779
    elif test "$HOST" = "eu.airvantage.net"
    then
        clientId=8439f64e239e4911ac2edee0f475d525
        clientSecret=ad4e7fce7fc7488da903206cda0415ce
    elif test "$HOST" = "na.airvantage.net"
    then
        clientId=0716ea3d63d34e49b69cabbd85db48ef
        clientSecret=c7621399f4e34003aa3ed30453524e65
    else
        echo
        echo "Unknown hostname."
        echo
        echo "Possible hostnames are:"
        echo "    --> na.airvantage.net"
        echo "    --> eu.airvantage.net"
        echo "    --> edge.airvantage.net"
        echo "    --> dev-airlink.airvantage.net"
        echo "    --> qa-branch.airvantage.net"
        echo "    --> qa-trunk.airvantage.net"
        echo
        exit 1
    fi
}



########################################################################################################################
# Indicates whether given args contain "--uid-only" or not.
#     --> Out: $args_uid_only
########################################################################################################################

_args_uid_only () {
    args_uid_only=0
    for i in $*
    do
        if test "$i" = "--uid-only"
        then
            args_uid_only=1
        fi
    done
}



########################################################################################################################
# Entities given in args
#     --> Out: $entities
########################################################################################################################

_entities () {
    entities="systems"
    for i in $*
    do
        j=`echo $i | awk -F/ '{print $2}'`
        if test -n "$j"
        then
            entities=$j
        fi
    done
}



########################################################################################################################
# Returns the template uid arg if present
#     --> Out: $template_uid
########################################################################################################################

_template_uid () {
    arg_found=0
    for i in $*
    do
        if test $arg_found -eq 1
        then
            template_uid=$i
            arg_found=0
        elif test "$i" = "--template-uid"
        then
            arg_found=1
        fi
    done
}



########################################################################################################################
# Shows help
########################################################################################################################

_help () {
    echo
    echo "Usage: av command [options]"
    echo
    echo "Available commands:"
    echo "    * av ssh"
    echo "    * av ls"
    echo "    * av find"
    echo "    * av cat"
    echo "    * av touch"
    echo "    * av vi"
    echo "    * av rm"
    echo
    echo "For a complete documentation of these commands, please refer to: https://github.com/bmiegemolle/airvantage-api-shell"
    echo
}



########################################################################################################################
# Retrieve an access token, and store it in a /tmp file used by further av commands
#     --> $2: host --> the host name, such as qa-trunk.airvantage.net
########################################################################################################################

_ssh () {
    HOST=$2

    _api_client $*
    
    echo -n "username: "
    read USERNAME
    echo -n "password: "
    read -s PASSWORD
    echo

    curl -s "https://$HOST/api/oauth/token?grant_type=password&username=$USERNAME&password=$PASSWORD&client_id=$clientId&client_secret=$clientSecret" | jq '.access_token' | awk -F\" '{print $2}' > $ACCESS_TOKEN_FILE
    
    if test -z `cat $ACCESS_TOKEN_FILE`
    then
        echo
        echo "A problem occurred while requesting an access token"
        echo
        exit 1
    fi

    echo "https://$HOST/api/v1" > $API_URL_FILE

    echo
    echo "Access granted! You can now use av commands!"
    echo "    --> API URL: `cat $API_URL_FILE`"
    echo "    --> Access token: `cat $ACCESS_TOKEN_FILE`"
    echo
}



########################################################################################################################
# Displays the details of the user associated with the current OAuth token
########################################################################################################################

_whoami () {
    BASE_URL=`cat $API_URL_FILE`
    ACCESS_TOKEN=`cat $ACCESS_TOKEN_FILE`
    
    curl -s "$BASE_URL/users/current?access_token=$ACCESS_TOKEN" | jq -c '.'
}



########################################################################################################################
# List all entities (systems by default)
#     --> $*: /entities --> the entities to list (/systems by default)
#             --uid-only --> whether only the uid should be displayed or the whole entities
########################################################################################################################

_ls () {
    BASE_URL=`cat $API_URL_FILE`
    ACCESS_TOKEN=`cat $ACCESS_TOKEN_FILE`
    
    _args_uid_only $*
    _entities $*
    
    if test $args_uid_only -eq 1
    then
        curl -s "$BASE_URL/$entities?access_token=$ACCESS_TOKEN" | jq -c '.items[] | {uid}' | awk -Fuid '{print $2}' | awk -F\" '{print $3}'
    else
        curl -s "$BASE_URL/$entities?access_token=$ACCESS_TOKEN" | jq -c '.items[] | {uid}'
    fi
}



########################################################################################################################
# Find entities (systems by default)
#     --> $2: -field --> the field to filter
#     --> $3: value --> the filter value
#     --> $*: /entities --> the entities to list (/systems by default)
#             --uid-only --> whether only the uid should be displayed or the whole entities
########################################################################################################################

_find () {
    BASE_URL=`cat $API_URL_FILE`
    ACCESS_TOKEN=`cat $ACCESS_TOKEN_FILE`
    
    FIELD=`echo $2 | awk -F- '{print $2}'`
    VALUE=$3

    _args_uid_only $*
    _entities $*

    if test $args_uid_only -eq 1
    then
        curl -s "$BASE_URL/$entities?$FIELD=$VALUE&access_token=$ACCESS_TOKEN" | jq -c ".items[] | {uid, $FIELD}" | awk -Fuid '{print $2}' | awk -F\" '{print $3}'
    else
        curl -s "$BASE_URL/$entities?$FIELD=$VALUE&access_token=$ACCESS_TOKEN" | jq -c ".items[] | {uid, $FIELD}"  
    fi
}



########################################################################################################################
# Get entity details
#     --> $2: the entities/uid to display. Possibilities are:
#                  /entities
#                  /entities/uid
#                  uid
#              if entities is not specified, then systems are queries by default
#              if uid is not specified, then uids are retrieved from standard input
########################################################################################################################

_cat () {
    BASE_URL=`cat $API_URL_FILE`
    ACCESS_TOKEN=`cat $ACCESS_TOKEN_FILE`
    
    _entities $*

    if test -n "`echo $2 | awk -F/ '{print $3}'`"
    then
        ID=`echo $2 | awk -F/ '{print $3}'`
    elif test -z "`echo $2 | awk -F / '{print $2}'`"
    then
        ID=$2
    else
        ID=""
    fi

    if test -n "$ID"
    then
        curl -s "$BASE_URL/$entities?uid=$ID&access_token=$ACCESS_TOKEN" | jq -c '.items[]'
    else
        EXIT=0
        while test $EXIT -eq 0
        do
            read ID
            EXIT=$?
            if test $EXIT -eq 0
            then
                curl -s "$BASE_URL/$entities?uid=$ID&access_token=$ACCESS_TOKEN" | jq -c '.items[]'
            fi
        done
    fi
}



########################################################################################################################
# Create an entity
#     --> $*: /entities --> the type of entity to create (/systems by default)
#             --template-uid uid --> the uid of the entity to use as a template
########################################################################################################################

_touch () {
    BASE_URL=`cat $API_URL_FILE`
    ACCESS_TOKEN=`cat $ACCESS_TOKEN_FILE`
    
    _entities $*
    _template_uid $*

    if test -n "$template_uid"
    then
        curl -s "$BASE_URL/$entities?uid=$template_uid&access_token=$ACCESS_TOKEN" | jq '.items[]' > $VI_FILE
    else
        echo "{ }" > $VI_FILE
    fi
 
    lastModificationTimeBeforeVi=`stat $VI_FILE -c "%Y"`
    vi $VI_FILE
    lastModificationTimeAfterVi=`stat $VI_FILE -c "%Y"`

    if test $lastModificationTimeAfterVi -gt $lastModificationTimeBeforeVi
    then
        curl -s "$BASE_URL/$entities?access_token=$ACCESS_TOKEN" -H 'Content-Type: application/json' -d "`cat $VI_FILE`" | jq -c .
    fi
}



########################################################################################################################
# Edit entity details
#     --> $2: the entities/uid to edit. Possibilities are:
#                  /entities/uid
#                  uid
#              if entities is not specified, then systems are queries by default
########################################################################################################################

_vi () {
    BASE_URL=`cat $API_URL_FILE`
    ACCESS_TOKEN=`cat $ACCESS_TOKEN_FILE`
    
    _entities $*

    if test -n "`echo $2 | awk -F/ '{print $3}'`"
    then
        ID=`echo $2 | awk -F/ '{print $3}'`
    elif test -z "`echo $2 | awk -F / '{print $2}'`"
    then
        ID=$2
    else
        ID=""
    fi

    if test -n "$ID"
    then
        curl -s "$BASE_URL/$entities?uid=$ID&access_token=$ACCESS_TOKEN" | jq '.items[]' > $VI_FILE
    fi
 
    lastModificationTimeBeforeVi=`stat $VI_FILE -c "%Y"`
    vi $VI_FILE
    lastModificationTimeAfterVi=`stat $VI_FILE -c "%Y"`

    if test $lastModificationTimeAfterVi -gt $lastModificationTimeBeforeVi
    then
        curl -s "$BASE_URL/$entities/$ID?access_token=$ACCESS_TOKEN" -H 'Content-Type: application/json' -X PUT -d "`cat $VI_FILE`" | jq -c .
    fi
}



########################################################################################################################
# Delete an entity
#     --> $2: the entities/uid to remove. Possibilities are:
#                  /entities/uid
#                  uid
#              if entities is not specified, then systems are candidate by default
########################################################################################################################

_rm () {
    BASE_URL=`cat $API_URL_FILE`
    ACCESS_TOKEN=`cat $ACCESS_TOKEN_FILE`
    
    _entities $*

    if test -n "`echo $2 | awk -F/ '{print $3}'`"
    then
        ID=`echo $2 | awk -F/ '{print $3}'`
    elif test -z "`echo $2 | awk -F / '{print $2}'`"
    then
        ID=$2
    else
        ID=""
    fi

    if test -n "$ID"
    then
        curl -s "$BASE_URL/$entities/$ID?access_token=$ACCESS_TOKEN" -X DELETE | jq -c .
    fi
}



########################################################################################################################
# Main
########################################################################################################################

if test $# -eq 0
then
    _help
    exit 1
fi

case "$1" in
    "help")
        _help
        ;;
    "ssh")
        _ssh $*
        ;;
    "whoami")
        _whoami $*
        ;;
    "ls")
        _ls $*
        ;;
    "find")
        _find $*
        ;;
    "cat")
        _cat $*
        ;;
    "touch")
        _touch $*
        ;;
    "vi")
        _vi $*
        ;;
    "rm")
        _rm $*
        ;;
    *)
        _help
        exit 1
        ;;
esac

